# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
